[package]
name = "checklist"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
colored = "3.0.0"
inquire = "0.9.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[[bin]]
name = "checklist"
path = "main.rs"
